services:
  - type: web
    name: resumatch-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false # Updated configuration
